# Generated by Django 4.2.8 on 2024-01-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=300)),
                ('category_is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'db_table': 'product_category_tbl',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=300)),
                ('product_price', models.FloatField(default=0)),
                ('product_stock_quantity', models.IntegerField(default=0)),
                ('product_is_active', models.BooleanField(default=True)),
                ('product_registered_date', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.productcategories')),
            ],
            options={
                'verbose_name': 'Products',
                'db_table': 'products_tbl',
            },
        ),
    ]
