# Generated by Django 4.2.8 on 2024-01-01 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supliers_name', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Product Supliers',
                'db_table': 'product_supliers_tbl',
            },
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_quantity', models.IntegerField(default=0)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.product')),
                ('purchase_suplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.productsupliers')),
            ],
            options={
                'verbose_name': 'Purchases',
                'db_table': 'products_purchase_tbl',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_customer_name', models.CharField(blank=True, max_length=300)),
                ('order_quantity', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.product')),
            ],
            options={
                'verbose_name': 'Orders',
                'db_table': 'products_orders_tbl',
            },
        ),
    ]
